# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bfb4bbee091d7f044a307bf6f36ba3ae6b5df44f544b23ecf32349d0a9c0a25b46f59217285b49e5222981c3a0b435887b566294e5d88dd133658d3f95af692

test:
  secret_key_base: b6b099f2ae3541f6b576e5b496bf2d2db94aa2eea825226d374d8dc4322d9080778166db1abbace3a7bc844b10a23160526f142a74a4c2a6a1b9c230d9f41ce2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
